apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- ../image-defaulter
resources:
- ../../../kustomize/base/admin-ui
- ../../../kustomize/base/end-user-ui
- ../../../kustomize/base/login-ui
